export const HOME = '/';
export const ABOUT = '/about';
export const GTa = '/global-talent';
export const GV = '/global-volunteer';
export const GTe = '/global-teacher';
export const AM ='/AIESEC-member';
export const OPPORTUNITIES = '/opportunities';
export const ORGANIZATIONS = '/for-organizations';
export const MEMBERSHIP = '/membership';